### PR TITLE
Improvements by rfleschenberg

### PR DESCRIPTION
**Pull request by ringe**
Thanks.

### CODE REVIEW

**Comment by ringe** [comment]
@rfleschenberg Thank you. Are you putting this to use?

**Comment by rfleschenberg** [comment]
Hey @ringe. Yes, I am using it to deploy a small mailserver (about 60 mailbox accounts, about 300 aliases).

**Comment by ringe** [comment]
Sweet. I had been looking at a lot of different approaches when I found this and cloned it to github.
I am using that and https://github.com/ringe/ispmail-on-rails in production on a small mailserver myself.

**Comment by rfleschenberg** [comment]
I'm happy to see that you're still maintaining this. If I make improvements in the future, I will send a PR.

I'm also using ispmail-on-rails with this. One thing that it's missing for me is the possibility to give people management permissions for certain domains only. Unfortunately, I don't know Ruby, but maybe I can find the time to add that feature one day.

**Comment by ringe** [comment]
Yeah, I can see that one easily. I might have time to put it in there in a couple of months. In the meantime feel free to look at https://github.com/thoughtbot/clearance/ after starting with ruby at https://www.codeschool.com/courses/try-ruby

**Pull request merged**
